version: '2'
services:
  staff-manager-api:
    container_name: staff-manager-admin-ui
    image: mchekini/staff-manager-admin-ui:${TAG}
    ports:
      - "81:80"

networks:
  default:
    external:
      name: staff-manager